parameters:
 - name: sourceServiceConnection
   type: string
   default: 'appreg-beisdev-tst-vertointernal-devops-azurerm'
 - name: destinationServiceConnection
   type: string
   default: 'appreg-beisdev-tst-vertointernal-devops-azurerm'
 - name: sourceStorageAccount
   type: string
   default: 'rgbeisdevukscorpdtp984b'
 - name: destinationStorageAccount
   type: string
   default: 'sabeisdevukststintgr'
 - name: sourceFileShare
   type: string
   default: 'logicapp-beisdev-uk-dev-vertointegration9535'
 - name: destinationFileShare
   type: string
   default: 'app-beisdev-uks-tst-verto-internal-integration-content'